<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- this is the native format of hnb (http://hnb.sourceforge.net/) -->
<!-- generated by hnb 1.5pre5 -->

<!DOCTYPE tree[
	<!ELEMENT tree (node*)>
	<!ELEMENT data (#PCDATA)>
	<!ELEMENT node (data?,node*)>
	<!ATTLIST node done (yes|no) #IMPLIED priority (1|2|3|4|5|6|7|8|9) #IMPLIED>
	<!-- maximum line length: 4096 -->
]>

<tree>
<node><data>&lt;!-- &lt;!doctype sect1 public &quot;-//OASSIS//DTD DocBook V4.0//EN&quot;&gt;</data></node>
<node><data>&lt;sect1 id=&quot;introduction&quot;&gt;</data>
	<node><data>&lt;title&gt;</data>
		<node><data>What is The &lt;application&gt;GIMP&lt;/application&gt;</data></node>
	</node>
	<node><data>&lt;indexterm&gt;</data>
		<node><data>&lt;primary&gt;GIMP</data></node>
		<node><data>&lt;secondary&gt;Introduction</data></node>
	</node>
	<node><data>&lt;para&gt;</data>
		<node><data>The</data></node>
		<node><data>&lt;ulink url=&quot;http://www.gimp.org/&quot; type=&quot;http&quot;&gt;</data>
			<node><data>&lt;application&gt;</data>
				<node><data>&lt;acronym&gt;GIMP</data></node>
			</node>
		</node>
		<node><data>is an acronym for</data></node>
		<node><data>&lt;ulink url=&quot;http://www.gnu.org/&quot; type=&quot;http&quot;&gt;</data>
			<node><data>&lt;acronym&gt;GNU</data></node>
		</node>
		<node><data>Image Manipulation Program. The</data></node>
		<node><data>&lt;application&gt;GIMP</data></node>
		<node><data>is an application suitable for such tasks as retouching of photographs, composing and authoring of images. Its capabilities as an image manipulation program make it a worthy competitor to other similar programs such as Adobe</data></node>
		<node><data>&lt;application&gt;Photoshop</data></node>
		<node><data>or Corel</data></node>
		<node><data>&lt;application&gt;PhotoPaint</data></node>
	</node>
	<node><data>&lt;para&gt;</data>
		<node><data>This is how and why</data></node>
		<node><data>&lt;application&gt;GIMP</data></node>
		<node><data>is constantly being developed and improved, not only by it&apos;s core developers, but a large amount of contributers and users.</data></node>
	</node>
	<node><data>&lt;sect2&gt;</data>
		<node><data>&lt;title&gt;A Brief List of Features and Capabilities</data></node>
		<node><data>&lt;para&gt;</data>
			<node><data>&lt;itemizedlist&gt;</data>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Full suite of painting tools including brushes, a pencil, an airbrush, an ink tool, and cloning.</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Tile-based memory management so image size is limited only by available disk space.</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Sub-pixel sampling for all paint tools, allowing for high-quality anti-aliasing.</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Full Alpha channel (transparency) support.</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Layers and channels.</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Advanced scripting capabilities provided by a procedural database so you can call internal</data></node>
					<node><data>&lt;application&gt;GIMP</data></node>
					<node><data>functions from external scripts, such as Script-Fu, Perl-Fu (Perl scripts) and Python-Fu (Python scripts).</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Multiple undo and redo, limited only by disk space.</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Transformation tools including rotate, scale shear and flip.</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;File formats supported include Poscript,</data></node>
					<node><data>&lt;acronym&gt;JPEG</data></node>
					<node><data>,</data></node>
					<node><data>&lt;acronym&gt;GIF</data></node>
					<node><data>,</data></node>
					<node><data>&lt;acronym&gt;PNG</data></node>
					<node><data>,</data></node>
					<node><data>&lt;acronym&gt;XPM</data></node>
					<node><data>,</data></node>
					<node><data>&lt;acronym&gt;TIFF</data></node>
					<node><data>,</data></node>
					<node><data>&lt;acronym&gt;TGA</data></node>
					<node><data>,</data></node>
					<node><data>&lt;acronym&gt;MPEG</data></node>
					<node><data>,</data></node>
					<node><data>&lt;acronym&gt;PCX</data></node>
					<node><data>,</data></node>
					<node><data>&lt;abbrev&gt;BMP</data></node>
					<node><data>and many others</data></node>
					<node><data></data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Selection tools including rectangular, elliptical, free, fuzzy, paths, and intelligent scissors.</data></node>
				</node>
				<node><data>&lt;listitem&gt;</data>
					<node><data>&lt;para&gt;Plug-ins that allow for the easy addition of new functinos, new file formats, and new effects filters.</data></node>
				</node>
			</node>
		</node>
	</node>
	<node><data>&lt;sect2&gt;</data>
		<node><data>&lt;title&gt;Platform Support</data></node>
		<node><data>&lt;para&gt;The</data>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>is probably most known for its use of the GNU/Linux platform, but there are many platforms that</data></node>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>can run on.</data></node>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>is known to work on</data></node>
			<node><data>&lt;productname&gt;GNU/Linux</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;Microsoft Windows 95,98,NT4 and 200</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;OpenBSD</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;NetBSD</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;FreeBSD</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;Solaris</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;SunOS</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;AIX</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;HP-UX</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;Tru64</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;Digital Unix</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;OSF/1</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;IRIX</data></node>
			<node><data>,</data></node>
			<node><data>&lt;productname&gt;OS/2</data></node>
			<node><data>and</data></node>
			<node><data>&lt;productname&gt;BeOS</data></node>
		</node>
		<node><data>&lt;para&gt;Porting</data>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>to other platforms is possible only due to source code availability.</data></node>
		</node>
	</node>
	<node><data>&lt;sect2&gt;</data>
		<node><data>&lt;title&gt;About the Help System</data></node>
		<node><data>&lt;para&gt;The</data>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>help system will provide you with the neccessarry information on how to use all the functions</data></node>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>provides. It will do so in a short effective way best described as an extended quick reference. The difference between the</data></node>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>help system and a pure quick reference is that the help system will describe how to use the functions in a productive manner as well as their functionality.</data></node>
		</node>
		<node><data>&lt;sect3&gt;</data>
			<node><data>&lt;title&gt;What to Expect of the Help System</data></node>
			<node><data>&lt;para&gt;Besides the description of the functionality of the functions in The</data></node>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>, you will also find descriptions of how to organize your work with</data></node>
			<node><data>&lt;application&gt;GIMP</data></node>
			<node><data>,how to configure it, various tips and tricks, a quick reference page of short cuts and modifier keys, and much more.</data></node>
		</node>
	</node>
</node>
<node><data>&lt;!-- some random notes about this file</data>
	<node><data>it is the real introduction to gimp manual</data></node>
</node>
<node><data>I typed it in to have a reference point to general xml editing capabilities in hnb, even tough it&apos;s sgml,.. it is also xml because of the way the gimp-help project makes it&apos;s files</data></node>
<node><data>ideas for how to make this file into xml:</data>
	<node><data>xml tags are only created when a node starts with &lt;tag attrs..&gt;</data></node>
	<node><data>the enclosing &lt;/tag&gt; is calculated and attributes subtracted</data></node>
	<node><data>inline tags &lt;example&gt;like this&lt;/example&gt; should be sput out as is.. (or should thay not?)</data></node>
	<node><data>nodes beginning with &lt;!-- (comments) are included verbatim as the plain ascii export.</data></node>
</node>
</tree>
